In [1]:
import pandas as pd

In [2]:
kar = pd.read_excel("pakistan_aqi_weather.xlsx", sheet_name = "Karachi")

In [3]:
kar['time'] = pd.to_datetime(kar['time'])

In [9]:
print(kar["time"].dtype)

datetime64[ns]

In [10]:
#kar = kar.set_index("time")

In [22]:
hourly = kar.groupby(kar['time'].dt.hour)['pm2_5'].mean()

In [24]:
hourly.tail()

time
19    31.978251
20    32.007876
21    31.694364
22    31.514884
23    31.425361
Name: pm2_5, dtype: float64

In [19]:
daily = kar.groupby(kar['time'].dt.date)['pm2_5'].mean()

In [21]:
daily.tail()

time
2026-05-14    12.866667
2026-05-15    12.200000
2026-05-16    19.133333
2026-05-17    22.808333
2026-05-18    22.333333
Name: pm2_5, dtype: float64

In [4]:
monthly = kar.groupby(kar['time'].dt.to_period('M'))['pm2_5'].sum()
print(monthly.tail())

time
2026-01    27047.8
2026-02    22448.1
2026-03    18866.1
2026-04    17299.8
2026-05    10290.8
Freq: M, Name: pm2_5, dtype: float64

In [5]:
monthly

time
2022-01        0.0
2022-02        0.0
2022-03        0.0
2022-04        0.0
2022-05        0.0
2022-06        0.0
2022-07        0.0
2022-08    22462.5
2022-09    19940.6
2022-10    27628.7
2022-11    35472.7
2022-12    42747.6
2023-01    38964.9
2023-02    33906.9
2023-03    35126.7
2023-04    17246.0
2023-05    13533.8
2023-06    15294.0
2023-07    19389.3
2023-08    13724.0
2023-09    18235.2
2023-10    20024.1
2023-11    35421.7
2023-12    25327.3
2024-01    32490.7
2024-02    19688.1
2024-03    18844.0
2024-04    14993.1
2024-05    12841.9
2024-06    15778.4
2024-07    22308.2
2024-08    14826.6
2024-09    14176.0
2024-10    18110.8
2024-11    21971.1
2024-12    29119.9
2025-01    30146.6
2025-02    19796.5
2025-03    16554.9
2025-04    16669.5
2025-05    18239.9
2025-06    19166.0
2025-07    20152.6
2025-08    17962.5
2025-09    16576.0
2025-10    23118.4
2025-11    29123.6
2025-12    28143.2
2026-01    27047.8
2026-02    22448.1
2026-03    18866.1
2026-04    17299.8
2026-05    10290.8
Freq: M, Name: pm2_5, dtype: float64

In [25]:
yearly = kar.groupby(kar['time'].dt.year)['pm2_5'].mean()
yearly.head()

time
2022    41.238414
2023    32.670537
2024    26.770128
2025    29.183756
2026    28.971196
Name: pm2_5, dtype: float64

In [26]:
yearly = kar.groupby(kar['time'].dt.year)['pm2_5'].mean()
yearly.head()

time
2022    41.238414
2023    32.670537
2024    26.770128
2025    29.183756
2026    28.971196
Name: pm2_5, dtype: float64

In [27]:
def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Autumn'

kar['season'] = kar['time'].dt.month.apply(get_season)

# Seasonal aggregation
seasonal_summary = kar.groupby('season')[
    [
        'pm2_5',
        'pm10',
        'temperature_2m',
        'relative_humidity_2m',
        'wind_speed_10m',
        'rain'
    ]
].agg(['mean', 'max', 'min'])

print(seasonal_summary)

            pm2_5                   pm10             temperature_2m        \
             mean    max  min       mean    max  min           mean   max
season
Autumn  32.028262  215.6  7.0  61.001408  497.3  7.6      27.439217  40.2
Spring  24.707336  339.0  3.5  57.631678  504.8  3.7      27.554139  41.5
Summer  24.833919  448.9  6.6  74.023618  642.6  8.1      29.494622  38.6
Winter  40.377147  290.6  0.4  61.607572  417.2  0.5      20.723065  31.4

             relative_humidity_2m          wind_speed_10m             \
         min                 mean  max min           mean   max  min
season
Autumn  15.8            67.869391  100   6      13.452370  38.2  0.0
Spring  10.0            68.994128  100   5      15.732858  45.1  0.2
Summer  24.9            78.701766   98  23      19.625374  46.6  0.4
Winter   8.9            54.404563  100   5      11.365972  44.6  0.2

            rain
            mean   max  min
season
Autumn  0.018681  15.8  0.0
Spring  0.005089   7.8  0.0
Summer  0.148143  43.2  0.0
Winter  0.007212   8.7  0.0

In [35]:
daily_avg = kar.groupby(kar['time'].dt.date)[
    ['pm2_5', 'pm10', 'temperature_2m']
].mean()

daily_avg.head()

            pm2_5  pm10  temperature_2m
time
2022-01-01    NaN   NaN       17.529167
2022-01-02    NaN   NaN       17.925000
2022-01-03    NaN   NaN       19.216667
2022-01-04    NaN   NaN       19.041667
2022-01-05    NaN   NaN       17.858333

In [36]:
monthly_avg = kar.groupby(kar['time'].dt.to_period('M'))[
    ['pm2_5', 'pm10', 'ozone']
].mean()

monthly_avg.head()

         pm2_5  pm10  ozone
time
2022-01    NaN   NaN    NaN
2022-02    NaN   NaN    NaN
2022-03    NaN   NaN    NaN
2022-04    NaN   NaN    NaN
2022-05    NaN   NaN    NaN

In [37]:
kar['month'] = kar['time'].dt.month

seasonal = kar.groupby('month')[
    ['pm2_5', 'temperature_2m', 'relative_humidity_2m']
].mean()

seasonal.head()

           pm2_5  temperature_2m  relative_humidity_2m
month
1      43.229167       18.779328             53.525806
2      35.339086       22.364923             62.729019
3      30.037534       25.284301             63.107258
4      22.989028       27.698056             70.615278
5      20.610511       29.879754             73.707453

In [40]:
weather_pollution = kar.groupby(
    pd.cut(kar['temperature_2m'], bins=5)
)['pm2_5'].mean()

weather_pollution.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_12140\370989440.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  weather_pollution = kar.groupby(

temperature_2m
(8.867, 15.42]    41.125446
(15.42, 21.94]    41.942530
(21.94, 28.46]    28.601880
(28.46, 34.98]    27.498659
(34.98, 41.5]     33.488248
Name: pm2_5, dtype: float64

In [41]:
wind_pollution = kar.groupby(
    pd.cut(kar['wind_speed_10m'], bins=5)
)['pm2_5'].mean()

wind_pollution.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_12140\250543835.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  wind_pollution = kar.groupby(

wind_speed_10m
(-0.0466, 9.32]    35.868130
(9.32, 18.64]      30.942834
(18.64, 27.96]     25.577742
(27.96, 37.28]     21.872531
(37.28, 46.6]      21.706383
Name: pm2_5, dtype: float64

In [43]:
max_pollution = kar.groupby(
    kar['time'].dt.date
)['pm2_5'].max()
max_pollution.head()

time
2022-01-01   NaN
2022-01-02   NaN
2022-01-03   NaN
2022-01-04   NaN
2022-01-05   NaN
Name: pm2_5, dtype: float64

In [44]:
rain_effect = kar.groupby(
    kar['rain'] > 0
)['pm2_5'].mean()

rain_effect.head()

rain
False    31.179148
True     23.963806
Name: pm2_5, dtype: float64

In [45]:
summary = kar.groupby(kar['time'].dt.month)['pm2_5'].agg([
    'mean',
    'max',
    'min',
    'std'
])

print(summary.head())

           mean    max  min        std
time
1     43.229167  203.5  4.7  20.409903
2     35.339086  290.6  7.9  22.029480
3     30.037534  339.0  3.5  24.469246
4     22.989028  104.1  5.5  10.155146
5     20.610511   75.0  6.0   8.760129