In [1]:
import pandas as pd

In [2]:
lah = pd.read_excel("pakistan_aqi_weather.xlsx", sheet_name = "Lahore")

In [4]:
lah['time'] = pd.to_datetime(lah['time'])

In [5]:
print(lah["time"].dtype)

datetime64[ns]

In [6]:
hourly = lah.groupby(lah['time'].dt.hour)['pm2_5'].mean()

In [7]:
hourly.tail()

time
19    74.076517
20    81.186705
21    85.336922
22    88.273699
23    89.002457
Name: pm2_5, dtype: float64

In [8]:
daily = lah.groupby(lah['time'].dt.date)['pm2_5'].mean()

In [9]:
daily.tail()

time
2026-05-14    50.850000
2026-05-15    51.187500
2026-05-16    34.779167
2026-05-17    34.604167
2026-05-18    28.100000
Name: pm2_5, dtype: float64

In [10]:
monthly = lah.groupby(lah['time'].dt.to_period('M'))['pm2_5'].sum()
print(monthly.tail())

time
2026-01    112701.7
2026-02     54401.0
2026-03     33699.7
2026-04     19942.7
2026-05     21112.3
Freq: M, Name: pm2_5, dtype: float64

In [11]:
yearly = lah.groupby(lah['time'].dt.year)['pm2_5'].mean()
yearly.head()

time
2022    89.976106
2023    67.588219
2024    68.316963
2025    68.745868
2026    73.024577
Name: pm2_5, dtype: float64

In [12]:
yearly = lah.groupby(lah['time'].dt.year)['pm2_5'].mean()
yearly.head()

time
2022    89.976106
2023    67.588219
2024    68.316963
2025    68.745868
2026    73.024577
Name: pm2_5, dtype: float64

In [13]:
def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Autumn'

lah['season'] = lah['time'].dt.month.apply(get_season)

# Seasonal aggregation
seasonal_summary = lah.groupby('season')[
    [
        'pm2_5',
        'pm10',
        'temperature_2m',
        'relative_humidity_2m',
        'wind_speed_10m',
        'rain'
    ]
].agg(['mean', 'max', 'min'])

print(seasonal_summary)

             pm2_5                    pm10             temperature_2m        \
              mean    max  min        mean    max  min           mean   max
season
Autumn   76.582543  365.1  7.5  106.631410  460.1  7.5      24.104224  38.6
Spring   43.168638  193.2  3.4   80.109425  845.6  3.6      26.403589  46.3
Summer   49.219805  199.3  3.8   92.623207  890.3  5.4      30.791474  46.5
Winter  111.267405  353.9  0.5  138.278751  459.1  0.6      13.357758  30.0

             relative_humidity_2m          wind_speed_10m             \
         min                 mean  max min           mean   max  min
season
Autumn   7.7            69.699405  100  21       6.170616  37.2  0.0
Spring   5.0            46.757550  100   5       8.469389  37.6  0.0
Summer  18.5            67.893569  100   4       7.843003  36.7  0.0
Winter   1.1            75.073810  100  16       6.002212  29.9  0.0

            rain
            mean   max  min
season
Autumn  0.058883  18.7  0.0
Spring  0.037994  15.0  0.0
Summer  0.210904  19.9  0.0
Winter  0.036200  15.5  0.0

In [14]:
daily_avg = lah.groupby(lah['time'].dt.date)[
    ['pm2_5', 'pm10', 'temperature_2m']
].mean()

daily_avg.head()

            pm2_5  pm10  temperature_2m
time
2022-01-01    NaN   NaN       11.104167
2022-01-02    NaN   NaN       11.241667
2022-01-03    NaN   NaN       12.787500
2022-01-04    NaN   NaN       12.970833
2022-01-05    NaN   NaN       12.562500

In [15]:
lah['month'] = lah['time'].dt.month

seasonal = lah.groupby('month')[
    ['pm2_5', 'temperature_2m', 'relative_humidity_2m']
].mean()

seasonal.head()

            pm2_5  temperature_2m  relative_humidity_2m
month
1      140.135988       10.730672             83.581720
2       72.839012       15.985106             65.414007
3       47.718212       21.306048             60.048656
4       35.502153       27.264250             40.470556
5       46.374324       31.058656             38.890845

In [16]:
weather_pollution = lah.groupby(
    pd.cut(lah['temperature_2m'], bins=5)
)['pm2_5'].mean()

weather_pollution.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_9428\3930006826.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  weather_pollution = lah.groupby(

temperature_2m
(1.055, 10.18]    151.702967
(10.18, 19.26]     95.675380
(19.26, 28.34]     56.989345
(28.34, 37.42]     47.819875
(37.42, 46.5]      35.969094
Name: pm2_5, dtype: float64

In [17]:
max_pollution = lah.groupby(
    lah['time'].dt.date
)['pm2_5'].max()
max_pollution.head()

time
2022-01-01   NaN
2022-01-02   NaN
2022-01-03   NaN
2022-01-04   NaN
2022-01-05   NaN
Name: pm2_5, dtype: float64

In [18]:
rain_effect = lah.groupby(
    lah['rain'] > 0
)['pm2_5'].mean()

rain_effect.head()

rain
False    73.026035
True     43.006181
Name: pm2_5, dtype: float64

In [20]:
summary = lah.groupby(lah['time'].dt.month)['pm2_5'].agg([
    'mean',
    'max',
    'min',
    'std'
])

print(summary.head())

            mean    max   min        std
time
1     140.135988  353.9  20.6  63.669491
2      72.839012  218.4  12.3  39.482214
3      47.718212  173.2   3.6  25.690562
4      35.502153  135.0   3.4  18.234467
5      46.374324  193.2  11.0  23.355161